package twozerofoureight.init;

public interface GlobalConstants {
	int X = 0;
	int Y = 1;
	int Z = 2;
	String JAVA2D = "processing.awt.PGraphicsJava2D";
	String P2D = "processing.opengl.PGraphics2D";
	String P3D = "processing.opengl.PGraphics3D";

	@Deprecated
	String OPENGL = "processing.opengl.PGraphics3D";
	String FX2D = "processing.javafx.PGraphicsFX2D";
	String PDF = "processing.pdf.PGraphicsPDF";
	String SVG = "processing.svg.PGraphicsSVG";
	String DXF = "processing.dxf.RawDXF";
	int OTHER = 0;
	int WINDOWS = 1;
	int MACOSX = 2;
	int LINUX = 3;
	String[] platformNames = new String[]{"other", "windows", "macosx", "linux"};
	float EPSILON = 1.0E-4F;
	float MAX_FLOAT = Float.MAX_VALUE;
	float MIN_FLOAT = -3.4028235E38F;
	int MAX_INT = Integer.MAX_VALUE;
	int MIN_INT = Integer.MIN_VALUE;
	int VERTEX = 0;
	int BEZIER_VERTEX = 1;
	int QUADRATIC_VERTEX = 2;
	int CURVE_VERTEX = 3;
	int BREAK = 4;

	@Deprecated
	int QUAD_BEZIER_VERTEX = 2;
	float PI = 3.1415927F;
	float HALF_PI = 1.5707964F;
	float THIRD_PI = 1.0471976F;
	float QUARTER_PI = 0.7853982F;
	float TWO_PI = 6.2831855F;
	float TAU = 6.2831855F;
	float DEG_TO_RAD = 0.017453292F;
	float RAD_TO_DEG = 57.295776F;
	String WHITESPACE = " \t\n\r\f ";
	int RGB = 1;
	int ARGB = 2;
	int HSB = 3;
	int ALPHA = 4;
	int TIFF = 0;
	int TARGA = 1;
	int JPEG = 2;
	int GIF = 3;
	int BLUR = 11;
	int POINT = 2;
	int LINE = 4;
	int LINES = 5;
	int LINE_STRIP = 50;
	int LINE_LOOP = 51;
	int TRIANGLE = 8;
	int QUAD = 16;
	int POLYGON = 20;
	int RECT = 30;
	int ELLIPSE = 31;
	int ARC = 32;
	int CIRCLE = 33;
	int SPHERE = 40;
	int OPEN = 1;
	int CLOSE = 2;
	int CORNER = 0;
	int CORNERS = 1;
	int RADIUS = 2;
	int CENTER = 3;
	int DIAMETER = 3;
	int CHORD = 2;
	int PIE = 3;
	int SQUARE = 1;
	char BACKSPACE = '\b';
	char TAB = '\t';
	char ENTER = '\n';
	char RETURN = '\r';
	char ESC = '';
	char DELETE = '';
	int CODED = 65535;
	int UP = 38;
	int DOWN = 40;
	int LEFT = 37;
	int RIGHT = 39;
	int ALT = 18;
	int CONTROL = 17;
	int SHIFT = 16;
	
	int WIDTH = 110;
	int GAP = 12;
}
